name: The Grid UX
favicon: null
layout_spectrum: 0.43786
typography_spectrum: 0
title: The Grid UX
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76486784-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8986752238124609
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.6985740985255688
purpose: []
